# Generated by Django 5.0.1 on 2025-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
