# Generated by Django 5.0.1 on 2025-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
    ]
